### ISSUE TITLE
Default FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by JasonKhew96** [jobobby04/TachiyomiSY#1142]
### Steps to reproduce

1. Launch TachiyomiSY from launcher.

### Expected behavior

TachiyomiSY should not crash

### Actual behavior

TachiyomiSY crashed

### Crash logs

```
================================================================
    Generated by AppErrorsTracking 1.3-59b835d(6)
    Project URL: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: google
[Device Model]: Pixel 8 Pro
[Display]: AP1A.240305.019.A1
[Android Version]: 14
[Android API Level]: 34
[System Locale]: en_SG
[Process ID]: 27463
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: eu.kanade.tachiyomi.sy.debug
[Version Name]: 1.10.5-8666
[Version Code]: 66
[Target SDK]: 34
[Min SDK]: 23
[Error Type]: JVM
[Crash Time]: 2024-03-28T22:25:55.243
[Stack Trace]:
java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7312)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
        at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:213)
        at com.google.firebase.crashlytics.ktx.FirebaseCrashlyticsKt.getCrashlytics(FirebaseCrashlytics.kt:38)
        at eu.kanade.tachiyomi.App.onCreate(App.kt:101)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1379)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7307)
        ... 9 more
```

### TachiyomiSY version

1.10.5-8666

### Android version

Android 14

### Device

Google Pixel 8 Pro

### Other details

I have use release version v1.10.5 for days and suffered crash after some actions, try to build a debug version from master branch (https://github.com/jobobby04/TachiyomiSY/commit/fb1649125cd4fce6843ede61862de195b393f1d1), but it crashed after launch

possible related issue: https://github.com/jobobby04/TachiyomiSY/issues/1139

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by JasonKhew96** [comment]
`Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.`

**Comment by JasonKhew96** [comment]
standard flavor master branch didn't crash, closing...
