### ISSUE TITLE
crash on extension installation using shizuku

### ISSUE THREAD

**Issue by AminurAlam** [jobobby04/TachiyomiSY#1296]
### Steps to reproduce

1. turn on shizuku installer
2. install any extension

### Expected behavior

no crash

### Actual behavior

crashes after installation finishes

### Crash logs

```
App version: 1.10.5 (standard, 106f63a65, 69, 2024-10-27T03:48:32Z)
Preview build: 568
Android version: 14 (SDK 34; build UP1A.231005.007.A346EXXS8CXIA)
Device brand: samsung
Device manufacturer: samsung
Device name: a34x (a34xdxx)
Device model: SM-A346E
WebView: Android System WebView 130.0.6723.58

java.lang.Throwable: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@b169125: java.lang.UnsupportedOperationException
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
	... 9 more


--------- beginning of crash
10-27 10:59:05.801  2314  2314 E AndroidRuntime: FATAL EXCEPTION: main
10-27 10:59:05.801  2314  2314 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 2314
10-27 10:59:05.801  2314  2314 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@c606e97: java.lang.UnsupportedOperationException
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
10-27 10:59:05.801  2314  2314 E AndroidRuntime: 	... 9 more
10-27 10:59:58.841 10768 10768 E AndroidRuntime: FATAL EXCEPTION: main
10-27 10:59:58.841 10768 10768 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 10768
10-27 10:59:58.841 10768 10768 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@bc4f5fb: java.lang.UnsupportedOperationException
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
10-27 10:59:58.841 10768 10768 E AndroidRuntime: 	... 9 more
10-27 11:01:59.831 14366 14366 E AndroidRuntime: FATAL EXCEPTION: main
10-27 11:01:59.831 14366 14366 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 14366
10-27 11:01:59.831 14366 14366 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@e2912fd: java.lang.UnsupportedOperationException
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
10-27 11:01:59.831 14366 14366 E AndroidRuntime: 	... 9 more
--------- beginning of main
10-27 11:03:19.965 15690 17380 E QT      : [QT]file does not exist
10-27 11:03:19.966 15690 17380 E QT      : [QT]file does not exist
10-27 11:03:20.063 15690 15690 E FBI     : Can't load library: dlopen failed: library "libmagtsync.so" not found
10-27 11:03:20.173 15690 15780 E SQLiteLog: (284) automatic index on C(manga_id)
10-27 11:03:20.173 15690 15780 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on C(manga_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on merged(manga_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on ME(merge_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on C(merge_id)
10-27 11:03:20.206 15690 15780 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
10-27 11:03:20.533 15690 17435 E ion     : ioctl c0044901 failed with code -1: Invalid argument
10-27 11:32:25.662 15690 15690 E AndroidRuntime: FATAL EXCEPTION: main
10-27 11:32:25.662 15690 15690 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 15690
10-27 11:32:25.662 15690 15690 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@b169125: java.lang.UnsupportedOperationException
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
10-27 11:32:25.662 15690 15690 E AndroidRuntime: 	... 9 more
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: java.lang.RuntimeException: Unable to stop service eu.kanade.tachiyomi.extension.util.ExtensionInstallService@b169125: java.lang.UnsupportedOperationException
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5318)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.app.ActivityThread.-$$Nest$mhandleStopService(Unknown Source:0)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2539)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.os.Looper.loopOnce(Looper.java:230)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:319)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:8919)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: Caused by: java.lang.UnsupportedOperationException
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1128)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at j$.util.Collection$-CC.$default$removeIf(SourceFile:546)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at j$.util.Collection$-EL.removeIf(Unknown Source:11)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.extension.installer.ShizukuInstaller.onDestroy(SourceFile:11)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.extension.util.ExtensionInstallService.onDestroy(SourceFile:5)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:5298)
10-27 11:32:25.663 15690 15690 E GlobalExceptionHandler: 	... 9 more
10-27 11:32:27.128 26242 26242 E de.tachiyomi.sy: Not starting debugger since process cannot load the jdwp agent.
10-27 11:32:27.281 26242 26285 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
10-27 11:32:27.312 26242 26308 E chromium: [1027/113227.312448:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
```

### TachiyomiSY version

App version: 1.10.5 (standard, 106f63a65, 69, 2024-10-27T03:48:32Z) Preview build: 568

### Android version

Android 14

### Device

Samsung

### Other details

App version: 1.10.5 (standard, 106f63a65, 69, 2024-10-27T03:48:32Z)
Preview build: 568
Android version: 14 (SDK 34; build UP1A.231005.007.A346EXXS8CXIA)
Device brand: samsung
Device manufacturer: samsung
Device name: a34x (a34xdxx)
Device model: SM-A346E
WebView: Android System WebView 130.0.6723.58

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https:/mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[1.10.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the latest build 👍
