### ISSUE TITLE
[Bug] <third crash>

### ISSUE THREAD

**Issue by dmswd** [jobobby04/TachiyomiSY#313]
## Device information
App version: 1.6.2 (standard, d04cdd9b3, 17)
Preview build: 368
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.A315FXXU1BUA1
Device brand: samsung
Device manufacturer: samsung
Device name: a31
Device model: SM-A315F
Device product name: a31xx

## Steps to reproduce
Reading chapter 27 of Pseudo Harem from mangadex

### Expected behavior
The app shouldn't crash

### Actual behavior
The app crashed

## Other details
Additional details and attachments.

Crash logs

--------- beginning of main 05-10 19:39:27.669 25409 25409 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-10 19:41:36.597 25409 25991 E gralloc : Arm Module v1.0 05-10 19:41:36.600 25409 25991 E ion : ioctl c0044901 failed with code -1: Invalid argument 05-10 19:41:38.822 25409 26093 E SQLiteLog: (284) automatic index on C(manga_id) 05-10 19:41:38.822 25409 26093 E SQLiteLog: (284) automatic index on R(manga_id) 05-10 19:41:38.823 25409 26093 E SQLiteLog: (284) automatic index on C(merge_id) 05-10 19:41:38.823 25409 26093 E SQLiteLog: (284) automatic index on R(merge_id) 05-10 19:41:38.823 25409 26093 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher 05-10 19:42:36.626 25409 26205 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 25409 05-10 19:42:36.626 25409 26205 E AndroidRuntime: java.lang.Error: java.lang.Exception: HTTP error 429 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1173) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: Caused by: java.lang.Exception: HTTP error 429 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$await$2$1.onResponse(OkHttpExtensions.kt:70) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 05-10 19:42:36.626 25409 26205 E AndroidRuntime: 	... 2 more 05-10 19:42:39.325 26244 26244 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent. 05-10 19:42:40.672 26244 26297 E SQLiteLog: (284) automatic index on C(manga_id) 05-10 19:42:40.672 26244 26297 E SQLiteLog: (284) automatic index on R(manga_id) 05-10 19:42:40.672 26244 26297 E SQLiteLog: (284) automatic index on C(merge_id) 05-10 19:42:40.672 26244 26297 E SQLiteLog: (284) automatic index on R(merge_id) 05-10 19:42:40.672 26244 26297 E SQLiteLog: (284) automatic index on mangas_categories(manga_id) 05-10 19:42:40.755 26244 26282 E gralloc : Arm Module v1.0 05-10 19:42:40.757 26244 26282 E ion : ioctl c0044901 failed with code -1: Invalid argument App version: 1.6.2 (standard, d04cdd9b3, 17) Preview build: 368 Android version: 10 (SDK 29) Android build ID: QP1A.190711.020.A315FXXU1BUA1 Device brand: samsung Device manufacturer: samsung Device name: a31 Device model: SM-A315F Device product name: a31xx

**Comment by dmswd** [comment]
Will close
Since I compared this crash log with that of #314
And they are the same
