### ISSUE TITLE
9e83130 breaks old extension repos from loading

### ISSUE THREAD

**Issue by ardittristan** [jobobby04/TachiyomiSY#471]
### Steps to reproduce

1. Add a third party repo, eg: `AriaMoradi/tachiyomi-unofficial-extensions`
2. Refresh extension list

### Expected behavior

Extensions should appear

### Actual behavior

Error retrieving extensions. No non-installed extensions appear.

### Crash logs
```
2021-12-20 12:31:40.512 E/StandaloneCoroutine: kotlinx.serialization.MissingFieldException: Field 'sources' is required for type with serial name 'eu.kanade.tachiyomi.extension.api.ExtensionJsonObject', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:3)
	at eu.kanade.tachiyomi.extension.api.ExtensionJsonObject.<init>(ExtensionGithubApi.kt:1)
	at eu.kanade.tachiyomi.extension.api.ExtensionJsonObject$$serializer.deserialize(ExtensionGithubApi.kt:1)
	at eu.kanade.tachiyomi.extension.api.ExtensionJsonObject$$serializer.deserialize(ExtensionGithubApi.kt:2)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:12)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:1)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:2)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:1)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:1)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:1)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:1)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:9)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:1)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:12)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:1)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:3)
	at eu.kanade.tachiyomi.extension.api.ExtensionGithubApi$findExtensions$2.invokeSuspend(ExtensionGithubApi.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```
### Tachiyomi version

r422

### Android version

Android 12L

### Device

Google Pixel 4

### Other details

9e83130
It seems older repos don't have the `sources` field in their json file.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.7.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Extension repos need to keep updated with the latest extension models.
@AriaMoradi your repo doesn't work on the latest preview

**Comment by AriaMoradi** [comment]
The repo is not being maintained, it's dormant/abandoned...

**Comment by jobobby04** [comment]
👌
