### ISSUE TITLE
Consistent crash when opening a manga from exh "UNIQUE constraint failed: history.history_chapter_id"

### ISSUE THREAD

**Issue by vetleledaal** [jobobby04/TachiyomiSY#672]
### Steps to reproduce

1. Open _that one_ manga
2. See details for a split second
3. Crash

Can only reproduce on one device, but only for _that one_ manga

### Expected behavior

Manga details and chapters are shown for more than a split second.

### Actual behavior

The app crashes shortly after showing manga details for a split second.

### Crash logs

--------- beginning of system
--------- beginning of crash
09-02 00:28:08.183  9922  9922 E AndroidRuntime: FATAL EXCEPTION: main
09-02 00:28:08.183  9922  9922 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 9922
09-02 00:28:08.183  9922  9922 E AndroidRuntime: com.pushtorefresh.storio.StorIOException: Error has occurred during Put operation. objects = [eu.kanade.tachiyomi.data.database.models.HistoryImpl@a19d7a6]
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:40)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$4$2.emit(Emitters.kt:58)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$3$2.emit(Emitters.kt:16)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2.emit(Emitters.kt:14)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2$1.invokeSuspend(Unknown Source:12)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:249)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:134)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a9f43c6, Dispatchers.Main]
09-02 00:28:08.183  9922  9922 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: history.history_chapter_id (code 2067)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:22)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.update(DefaultStorIOSQLite.java:9)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:5)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:1)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:17)
09-02 00:28:08.183  9922  9922 E AndroidRuntime: 	... 16 more
09-02 09:16:43.729 18786 18786 E AndroidRuntime: FATAL EXCEPTION: main
09-02 09:16:43.729 18786 18786 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 18786
09-02 09:16:43.729 18786 18786 E AndroidRuntime: com.pushtorefresh.storio.StorIOException: Error has occurred during Put operation. objects = [eu.kanade.tachiyomi.data.database.models.HistoryImpl@466ff22]
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:40)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$4$2.emit(Emitters.kt:58)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$3$2.emit(Emitters.kt:16)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2.emit(Emitters.kt:14)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2$1.invokeSuspend(Unknown Source:12)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:249)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:134)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9bfbfcb, Dispatchers.Main]
09-02 09:16:43.729 18786 18786 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: history.history_chapter_id (code 2067)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:22)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.update(DefaultStorIOSQLite.java:9)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:5)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:1)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:17)
09-02 09:16:43.729 18786 18786 E AndroidRuntime: 	... 16 more
--------- beginning of main
09-02 17:14:30.300  2395  2395 E SQLiteLog: (2067) abort at 31 in [UPDATE history SET history_chapter_id=? WHERE history_id = ?]: UNIQUE constraint failed: history.history_chapter_id
09-02 17:14:30.435  2395  2395 E AndroidRuntime: FATAL EXCEPTION: main
09-02 17:14:30.435  2395  2395 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 2395
09-02 17:14:30.435  2395  2395 E AndroidRuntime: com.pushtorefresh.storio.StorIOException: Error has occurred during Put operation. objects = [eu.kanade.tachiyomi.data.database.models.HistoryImpl@770f332]
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:40)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$4$2.emit(Emitters.kt:58)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$3$2.emit(Emitters.kt:16)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2.emit(Emitters.kt:14)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2$1.invokeSuspend(Unknown Source:12)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:1)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at android.os.Handler.handleCallback(Unknown Source:2)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Unknown Source:4)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:249)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:134)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:313)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a3fd05a, Dispatchers.Main]
09-02 17:14:30.435  2395  2395 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: history.history_chapter_id (code 2067)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at io.requery.android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:22)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.impl.DefaultStorIOSQLite$LowLevelImpl.update(DefaultStorIOSQLite.java:9)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:5)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.database.resolvers.HistoryChapterIdPutResolver.performPut(HistoryChapterIdPutResolver.kt:1)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	at com.pushtorefresh.storio.sqlite.operations.put.PreparedPutCollectionOfObjects.executeAsBlocking(PreparedPutCollectionOfObjects.java:17)
09-02 17:14:30.435  2395  2395 E AndroidRuntime: 	... 16 more
09-02 17:14:53.328  5853  5853 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
09-02 17:14:54.154  5853  5853 E SQLiteLog: (283) recovered 272 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
09-02 17:14:57.427  5853  5969 E SQLiteLog: (284) automatic index on C(manga_id)
09-02 17:14:57.427  5853  5969 E SQLiteLog: (284) automatic index on R(manga_id)
09-02 17:14:57.427  5853  5969 E SQLiteLog: (284) automatic index on C(merge_id)
09-02 17:14:57.427  5853  5969 E SQLiteLog: (284) automatic index on R(merge_id)
09-02 17:14:57.427  5853  5969 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.8.5 (standard, b7779ba, 36, 2022-08-14T19:51Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: cepheus
Device model: MI 9
Device product name: cepheus

### Tachiyomi version

1.8.5

### Android version

Android 11

### Device

Xiaomi Mi 9

### Other details

Appears to be the same crash as in #538, this is also a western comic. Manga says "Visible: Yes" and has 4 chapters on both the crashing and non-crashing device. I never migrated the manga.

I wouldn't mind losing progress if that means the app doesn't crash.

I can compile potential fixes and test as necessary.

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
I fixed this in the preview using the new database framework

**Comment by vetleledaal** [comment]
Gotcha, thought this was in stable since the other issue was closed in March
