### ISSUE TITLE
'could not find manga' toast on already tracked manga

### ISSUE THREAD

**Issue by lewdpatriot** [jobobby04/TachiyomiSY#745]
### Steps to reproduce

Click tracker icon on an already tracked manga (I use anilist). 

### Expected behavior

N/A

### Actual behavior

It shows 'could not find manga' toast. But the actual tracking works fine.
I have to remove the tracking and then add again to remove the toast. But it appears again in a couple of days.

### Tachiyomi version

1.8.5

### Android version

Android 11

### Device

Realme 6i

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jferdous70** [comment]
Can confirm, it also happens to me

**Comment by jobobby04** [comment]
Can you post logs?

**Comment by lewdpatriot** [comment]
`2022-11-29 01:46:54.690 E/MangaController: java.lang.Exception: Could not find manga
	at eu.kanade.tachiyomi.data.track.anilist.AnilistApi.getLibManga(AnilistApi.kt:4)
	at eu.kanade.tachiyomi.data.track.anilist.AnilistApi$getLibManga$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:10)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:50:49.513 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:50:49.513 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:51:14.137 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:51:14.138 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:51:59.473 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:51:59.473 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:52:07.058 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:52:07.058 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:52:17.659 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:52:17.659 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)`

**Comment by lewdpatriot** [comment]
> Can you post logs, either crash logs or TachiyomiSY/logs?

2022-11-29 01:46:54.690 E/MangaController: java.lang.Exception: Could not find manga
	at eu.kanade.tachiyomi.data.track.anilist.AnilistApi.getLibManga(AnilistApi.kt:4)
	at eu.kanade.tachiyomi.data.track.anilist.AnilistApi$getLibManga$1.invokeSuspend(Unknown Source:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:10)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:50:49.513 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:50:49.513 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:51:14.137 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:51:14.138 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:51:59.473 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:51:59.473 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:52:07.058 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:52:07.058 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)
2022-11-29 01:52:17.659 W/BrowseSourceController: 	├ exh.log.LoggingKt.xLogW(Logging.kt:4)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourceController.onAddPageError(BrowseSourceController.kt:1)
	├ eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1$1.invokeSuspend(BrowseSourcePresenter.kt:1)
	├ kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	├ kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	├ android.os.Handler.handleCallback(Handler.java:938)
	├ android.os.Handler.dispatchMessage(Handler.java:99)
	├ android.os.Looper.loop(Looper.java:255)
	├ android.app.ActivityThread.main(ActivityThread.java:8212)
	├ java.lang.reflect.Method.invoke(Native Method)
	├ com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	└ com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
> Failed to load next catalogue page!
eu.kanade.tachiyomi.ui.browse.source.browse.NoResultsException
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage$suspendImpl(SourcePager.kt:13)
	at eu.kanade.tachiyomi.ui.browse.source.browse.SourcePager.requestNextPage(Unknown Source:0)
	at eu.kanade.tachiyomi.ui.browse.source.browse.BrowseSourcePresenter$requestNext$1.invokeSuspend(BrowseSourcePresenter.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:2)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)

2022-11-29 01:52:17.659 W/BrowseSourceController: > (source.id: 7798162483793432927, source.name: MangaLife)

**Comment by jferdous70** [comment]
This is mine

[tachiyomi_crash_logs.txt](https://github.com/jobobby04/TachiyomiSY/files/10137086/tachiyomi_crash_logs.txt)

**Comment by jobobby04** [comment]
Can you post some example manga/anilist links? There isn't anything that i can see that would cause something like this

**Comment by jferdous70** [comment]
Queen Bee https://anilist.co/manga/114832/Jipjuin-Ttallaemi/. Toast appears no matter what i do (removing and readding doesn't matter)

**Comment by jobobby04** [comment]
Works on my device

**Comment by jferdous70** [comment]
this is reproducable on any device. Sy seems to be bugged for Anilist 

```
StandaloneCoroutine: at eu.kanade.tachiyomi.data.track.anilist.AnilistApi.getLibManga(AnilistApi.kt:75)

StandaloneCoroutine: at eu.kanade.tachiyomi.data.track.anilist.AnilistApi$getLibManga$1.invokeSuspend(Unknown Source:13
```

do you need a backup file? if it helps

**Comment by lewdpatriot** [comment]
@jferdous70 are you using preview build?  Preview build seems to work for me. But can't use it because it's very laggy on my device.

**Comment by lewdpatriot** [comment]
> Can you post some example manga/anilist links? There isn't anything that i can see that would cause something like this

It does that on all of my 70 tracked manga, so it's not about some specific titles. Btw preview build does not have the problem, but it's very laggy for me to use.

**Comment by jferdous70** [comment]
> @jferdous70 are you using preview build? Preview build seems to work for me. But can't use it because it's very laggy on my device.

I am. It still shows for some entries even if you remove them from tracker and add back. Shows HTTP Error 404 (as shown in log above)

**Comment by jferdous70** [comment]
i wonder if i should open a new issue?

**Comment by jobobby04** [comment]
Nope

**Comment by jobobby04** [comment]
> It does that on all of my 70 tracked manga, so it's not about some specific titles. Btw preview build does not have the problem, but it's very laggy for me to use.

If preview doesn't have this problem for you, then I would consider this solved, as preview is a beta of the next version of SY

**Comment by lewdpatriot** [comment]
Sorry it's happening again in 491, I tried 
reloging, updating tracker, clean install, disabling adblocker, installing it in another device but no luck. Maybe my backup is corrupted? But it's working fine in other forks.

Please tell if I can help in any way.

**Comment by jferdous70** [comment]
> Sorry it's happening again in 491, I tried reloging, updating tracker, clean install, disabling adblocker, installing it in another device but no luck. Maybe my backup is corrupted? But it's working fine in other forks.
> 
> Please tell if I can help in any way.

I can verify this. Restored my backup on main preview, and tracked the manhwa again on Anilist. It doesn't show HTTP error 404 toast on tracking sheet after retracking. 

The toast appears to be sy exclusive issue

**Comment by jobobby04** [comment]
It shouldn't be, SY uses the code from main Tachi and there is nothing different

**Comment by jferdous70** [comment]
I can share screen recording for both sy and main preview for demo, if necessary

**Comment by jobobby04** [comment]
No, there doesn't seem to be anything I can do anyway
