### ISSUE TITLE
Crash while browsing/changing category on EX

### ISSUE THREAD

**Issue by Ramzh** [jobobby04/TachiyomiSY#755]
### Steps to reproduce

1. Browse EX
2. Add entry to library
3. Hold on to it and change category
4. Keep browsing

### Expected behavior

No crashes

### Actual behavior

Crashes

### Crash logs

```
--------- beginning of crash
12-06 23:44:18.558 10825 10825 E AndroidRuntime: FATAL EXCEPTION: main
12-06 23:44:18.558 10825 10825 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 10825
12-06 23:44:18.558 10825 10825 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:47)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:89)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
12-06 23:44:18.558 10825 10825 E AndroidRuntime: 	... 9 more
12-07 08:12:57.140 16936 16936 E AndroidRuntime: FATAL EXCEPTION: main
12-07 08:12:57.140 16936 16936 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 16936
12-07 08:12:57.140 16936 16936 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:47)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:89)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
12-07 08:12:57.140 16936 16936 E AndroidRuntime: 	... 9 more
12-07 21:36:00.145 29739 29739 E AndroidRuntime: FATAL EXCEPTION: main
12-07 21:36:00.145 29739 29739 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 29739
12-07 21:36:00.145 29739 29739 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:47)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:89)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
12-07 21:36:00.145 29739 29739 E AndroidRuntime: 	... 9 more
--------- beginning of main
12-07 21:37:15.917 29989 30172 E GetManga: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c58e690
12-07 21:37:15.982 29989 29989 E GetChapterByUrl: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c58e690
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: java.util.NoSuchElementException
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$3$2.emit(Emitters.kt:127)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$2$2.emit(Emitters.kt:184)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$1$2.emit(Emitters.kt:177)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at exh.eh.EHentaiUpdateHelper$findAcceptedRootAndDiscardOthers$$inlined$map$1$2$1.invokeSuspend(Unknown Source:12)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:97)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at android.os.Handler.handleCallback(Handler.java:942)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at android.os.Looper.loopOnce(Looper.java:201)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:288)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-07 21:37:15.983 29989 29989 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Screen#2:eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel:default), StandaloneCoroutine{Cancelling}@7857f63, Dispatchers.Main]
12-07 21:37:16.117 30313 30313 E AndroidRuntime: FATAL EXCEPTION: main
12-07 21:37:16.117 30313 30313 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 30313
12-07 21:37:16.117 30313 30313 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6790)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:47)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:89)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6785)
12-07 21:37:16.117 30313 30313 E AndroidRuntime: 	... 9 more
12-07 21:37:28.335 30446 30483 E SQLiteLog: (283) recovered 139 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
12-07 21:37:28.709 30446 30587 E SQLiteLog: (284) automatic index on C(manga_id)
12-07 21:37:28.709 30446 30587 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on C(manga_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on merged(manga_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on ME(merge_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on C(merge_id)
12-07 21:37:33.469 30446 30587 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.8.5 (standard, 266b4c4dd, 44, 2022-12-05T20:17Z)
Preview build: 494
Android version: 13 (SDK 33)
Android build ID: TP1A.221105.002
Device brand: google
Device manufacturer: Google
Device name: bluejay
Device model: Pixel 6a
Device product name: bluejay
```

### Tachiyomi version

Preview 494

### Android version

Android 13

### Device

Google Pixel 6a

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Should be fixed in the latest build
