### ISSUE TITLE
Filter manga by "Downloaded" caused the app to crash

### ISSUE THREAD

**Issue by cyborgA0** [jobobby04/TachiyomiSY#769]
### Steps to reproduce

1. Filter manga by Downloaded(Downloaded and Unread)
2. Close the app(kill in recents)
3. Open app

### Expected behavior

The app should open normally with the filter

### Actual behavior

Crashes, doesn't even open anymore it's force closing. The only solution is to revert back to r493 version

### Crash logs
```kotlin
2022-12-21 17:29:28.447 D/App: Application booting...
2022-12-21 17:29:28.452 D/App: App version: 1.8.5 (standard, 33d5c0859, 44)
Preview build: 495
Android version: 12 (SDK 31) 
Android build ID: AL5186-selene-build-20220906012418
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: selene
Device model: 21061119AG
Device product name: selene_global
2022-12-21 17:29:29.341 D/NHentai: Delegating source: eu.kanade.tachiyomi.extension.all.nhentai.NHentai -> eu.kanade.tachiyomi.source.online.all.NHentai!
2022-12-21 17:29:29.355 D/NHentai: Delegating source: eu.kanade.tachiyomi.extension.all.nhentai.NHentai -> eu.kanade.tachiyomi.source.online.all.NHentai!
2022-12-21 17:29:29.355 D/NHentai: Delegating source: eu.kanade.tachiyomi.extension.all.nhentai.NHentai -> eu.kanade.tachiyomi.source.online.all.NHentai!
2022-12-21 17:29:29.355 D/NHentai: Delegating source: eu.kanade.tachiyomi.extension.all.nhentai.NHentai -> eu.kanade.tachiyomi.source.online.all.NHentai!
2022-12-21 17:29:29.359 D/HBrowse: Delegating source: eu.kanade.tachiyomi.extension.en.hbrowse.HBrowse -> eu.kanade.tachiyomi.source.online.english.HBrowse!
2022-12-21 17:29:29.381 D/MangaDexEnglish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexEnglish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.393 D/MangaDexArabic: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexArabic -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.394 D/MangaDexBengali: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexBengali -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.394 D/MangaDexBulgarian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexBulgarian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.395 D/MangaDexBurmese: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexBurmese -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.395 D/MangaDexCatalan: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexCatalan -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.396 D/MangaDexChineseSimp: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexChineseSimp -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.396 D/MangaDexChineseTrad: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexChineseTrad -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.397 D/MangaDexCzech: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexCzech -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.397 D/MangaDexDanish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexDanish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.398 D/MangaDexDutch: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexDutch -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.399 D/MangaDexFilipino: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFilipino -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.399 D/MangaDexFinnish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFinnish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.400 D/MangaDexFrench: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexFrench -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.401 D/MangaDexGerman: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexGerman -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.401 D/MangaDexGreek: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexGreek -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.402 D/MangaDexHebrew: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexHebrew -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.403 D/MangaDexHindi: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexHindi -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.403 D/MangaDexHungarian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexHungarian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.404 D/MangaDexIndonesian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexIndonesian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.405 D/MangaDexItalian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexItalian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.405 D/MangaDexJapanese: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexJapanese -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.406 D/MangaDexKazakh: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexKazakh -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.407 D/MangaDexKorean: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexKorean -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.408 D/MangaDexLatin: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexLatin -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.408 D/MangaDexLithuanian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexLithuanian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.409 D/MangaDexMalay: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexMalay -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.410 D/MangaDexMongolian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexMongolian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.411 D/MangaDexNepali: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexNepali -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.412 D/MangaDexNorwegian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexNorwegian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.413 D/MangaDexPersian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexPersian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.413 D/MangaDexPolish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexPolish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.414 D/MangaDexPortugueseBrazil: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexPortugueseBrazil -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.415 D/MangaDexPortuguesePortugal: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexPortuguesePortugal -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.416 D/MangaDexRomanian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexRomanian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.417 D/MangaDexRussian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexRussian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.418 D/MangaDexSerboCroatian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexSerboCroatian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.418 D/MangaDexSpanishLTAM: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexSpanishLTAM -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.419 D/MangaDexSpanishSpain: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexSpanishSpain -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.420 D/MangaDexSwedish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexSwedish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.421 D/MangaDexTamil: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexTamil -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.422 D/MangaDexThai: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexThai -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.423 D/MangaDexTurkish: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexTurkish -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.424 D/MangaDexUkrainian: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexUkrainian -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:29.425 D/MangaDexVietnamese: Delegating source: eu.kanade.tachiyomi.extension.all.mangadex.MangaDexVietnamese -> eu.kanade.tachiyomi.source.online.all.MangaDex!
2022-12-21 17:29:30.208 E/GlobalExceptionHandler: java.lang.IllegalStateException: currentPage cannot be less than zero
	at eu.kanade.presentation.components.PagerState.<init>(Pager.kt:4)
	at eu.kanade.presentation.components.PagerKt$rememberPagerState$1$1.invoke(Pager.kt:5)
	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:18)
	at eu.kanade.presentation.components.PagerKt.rememberPagerState(Pager.kt:65)
	at eu.kanade.presentation.library.components.LibraryContentKt.LibraryContent(LibraryContent.kt:50)
	at eu.kanade.tachiyomi.ui.library.LibraryTab$Content$4.invoke(LibraryTab.kt:483)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
	at androidx.compose.runtime.internal.ComposableLambdaImpl$invoke$1.invoke(ComposableLambda.jvm.kt:21)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:299)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:60)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:85)
	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:50)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:127)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:36)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:75)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:360)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:11)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1164)
	at android.view.Choreographer.doCallbacks(Choreographer.java:949)
	at android.view.Choreographer.doFrame(Choreographer.java:853)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@fe3e231, androidx.compose.ui.platform.MotionDurationScaleImpl@5d86d16, StandaloneCoroutine{Cancelling}@3675697, AndroidUiDispatcher@f2c1084]

2022-12-21 17:29:30.368 D/App: Application booting...
2022-12-21 17:29:30.371 D/App: App version: 1.8.5 (standard, 33d5c0859, 44)
Preview build: 495
Android version: 12 (SDK 31) 
Android build ID: AL5186-selene-build-20220906012418
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: selene
Device model: 21061119AG
Device product name: selene_global
```

### Tachiyomi version

r494 and r495

### Android version

Android 12

### Device

Xiaomi Redmi 10

### Acknowledgements

- [x] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.8.5](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the latest build
