### ISSUE TITLE
Error Cleaning the Database - TachiyomiYS version 1.9.0

### ISSUE THREAD

**Issue by deividgabrielpeira** [jobobby04/TachiyomiSY#794]
### Steps to reproduce

1. Go to Advanced
2. Clear the database (has a small chance of crashing the application)

### Expected behavior

Clearing the TachiyomiSY database will crash the application

### Actual behavior

It will crash the application and the only way is to restart the program 

### Crash logs
```
2023-02-10 09:13:21.559 E/MangaInfoScreenModel: java.net.UnknownHostException: Unable to resolve host "mangaschan.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:7)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:197)
	at okhttp3.internal.connection.RealRoutePlanner.plan(RealRoutePlanner.kt:191)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.launchTcpConnect(FastFallbackExchangeFinder.kt:13)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:66)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:30)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:179)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:228)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:154)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:44)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:18)
	at rx.Subscriber.setProducer(Subscriber.java:39)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:3)
	at rx.Subscriber.setProducer(Subscriber.java:22)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda1.call(R8$$SyntheticClass:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
	at rx.Observable.unsafeSubscribe(Observable.java:10)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
	at rx.Observable.subscribe(Observable.java:24)
	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:29)
	at eu.kanade.tachiyomi.source.Source$DefaultImpls.getMangaDetails(Source.kt:5)
	at eu.kanade.tachiyomi.source.online.HttpSource.getMangaDetails(HttpSource.kt:1)
	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel$fetchMangaFromSource$2.invokeSuspend(MangaScreenModel.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 48 more

2023-02-10 09:13:31.574 E/MangaInfoScreenModel: java.net.UnknownHostException: Unable to resolve host "mangaschan.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:7)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:197)
	at okhttp3.internal.connection.RealRoutePlanner.plan(RealRoutePlanner.kt:191)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.launchTcpConnect(FastFallbackExchangeFinder.kt:13)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:66)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:30)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:179)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:228)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.RateLimitInterceptor.intercept(RateLimitInterceptor.kt:154)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.WebViewInterceptor.intercept(WebViewInterceptor.kt:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:68)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:44)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:18)
	at rx.Subscriber.setProducer(Subscriber.java:39)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:3)
	at rx.Subscriber.setProducer(Subscriber.java:22)
	at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$$ExternalSyntheticLambda1.call(R8$$SyntheticClass:24)
	at rx.Observable.unsafeSubscribe(Observable.java:10)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:2)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:1)
	at rx.Observable.unsafeSubscribe(Observable.java:10)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:4)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:1)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:4)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:1)
	at rx.Observable.subscribe(Observable.java:24)
	at eu.kanade.tachiyomi.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:29)
	at eu.kanade.tachiyomi.source.Source$DefaultImpls.getChapterList(Source.kt:5)
	at eu.kanade.tachiyomi.source.online.HttpSource.getChapterList(HttpSource.kt:1)
	at eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel$fetchChaptersFromSource$2.invokeSuspend(MangaScreenModel.kt:55)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 48 more

2023-02-10 09:14:58.741 E/GlobalExceptionHandler: java.lang.NullPointerException: ResultSet returned null for mangas.sq:getMangaById
	at com.squareup.sqldelight.Query.executeAsOne(Query.kt:16)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$1$1.invokeSuspend(FlowExtensions.kt:6)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$1$1.invoke(FlowExtensions.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$$inlined$map$1$2.emit(Collect.kt:76)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:20)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Screen#0:eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@f561bbc, Dispatchers.IO]

2023-02-10 09:23:34.527 W/ExtensionLoader: Tried to load a package that wasn't a extension (com.facebook.orca)
2023-02-10 09:23:34.575 W/ExtensionLoader: Tried to load a package that wasn't a extension (com.facebook.orca)
2023-02-10 09:33:16.843 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@cd1225f

2023-02-10 09:33:19.917 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@cd1225f

2023-02-10 09:35:11.424 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c26557e

2023-02-10 09:35:14.426 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@c26557e

2023-02-10 09:35:17.195 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@4a01040

2023-02-10 09:35:20.115 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@4a01040

2023-02-10 09:35:23.129 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@8890a3f

2023-02-10 09:35:26.105 E/MangaInfoScreenModel: kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelling}@8890a3f

2023-02-10 09:37:16.565 E/GlobalExceptionHandler: java.lang.NullPointerException: ResultSet returned null for mangas.sq:getMangaById
	at com.squareup.sqldelight.Query.executeAsOne(Query.kt:16)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$1$1.invokeSuspend(FlowExtensions.kt:6)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$1$1.invoke(FlowExtensions.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:8)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:50)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToOne$$inlined$map$1$2.emit(Collect.kt:76)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:2)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:20)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$asFlow$1.invokeSuspend(FlowExtensions.kt:160)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:66)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Screen#10:eu.kanade.tachiyomi.ui.manga.MangaInfoScreenModel:default:ScreenModelCoroutineScope), StandaloneCoroutine{Cancelling}@19d2406, Dispatchers.IO]

```

### Tachiyomi version

1.9.0

### Android version

MIUI GLOBAL 14.0.1

### Device

POCO x4 GT

### Other details

no

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Seems to be unrelated to clearing the database specifically
