### ISSUE TITLE
App crashes when viewing gifs

### ISSUE THREAD

**Issue by patros36** [jobobby04/TachiyomiSY#833]
### Steps to reproduce

Open an artist containing just gifs (moving pictures, i presume they are gifs)
Scroll through the pages

### Expected behavior

Not crash

### Actual behavior

Crash

### Crash logs
```
--------- beginning of system
--------- beginning of crash
03-21 15:25:06.377  6208  6208 E AndroidRuntime: FATAL EXCEPTION: main
03-21 15:25:06.377  6208  6208 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 6208
03-21 15:25:06.377  6208  6208 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:44)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.addAnalytics(App.kt:26)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:85)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
03-21 15:25:06.377  6208  6208 E AndroidRuntime: 	... 8 more
03-21 15:26:28.943  6770  6770 E AndroidRuntime: FATAL EXCEPTION: main
03-21 15:26:28.943  6770  6770 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 6770
03-21 15:26:28.943  6770  6770 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:44)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.addAnalytics(App.kt:26)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:85)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
03-21 15:26:28.943  6770  6770 E AndroidRuntime: 	... 8 more
03-23 16:12:15.932 12556 12556 E AndroidRuntime: FATAL EXCEPTION: main
03-23 16:12:15.932 12556 12556 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 12556
03-23 16:12:15.932 12556 12556 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:44)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.addAnalytics(App.kt:26)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:85)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
03-23 16:12:15.932 12556 12556 E AndroidRuntime: 	... 8 more
--------- beginning of main
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.sy/cache/chapter_disk_cache/a61540bf262f4cd133291177f508433b.0: open failed: ENOENT (No such file or directory)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:496)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(HttpPageLoader.kt:37)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerPageHolder$setImage$2.invokeSuspend(PagerPageHolder.kt:6)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1c31848, Dispatchers.Main]
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.Linux.open(Native Method)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:482)
03-23 19:19:24.213  7676  7676 E GlobalExceptionHandler: 	... 9 more
03-23 19:19:24.858  9267  9267 E y:error_handle: Unknown bits set in runtime_flags: 0x8000
03-23 19:19:24.860  9267  9267 E y:error_handle: Not starting debugger since process cannot load the jdwp agent.
03-23 19:19:24.915  9267  9267 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
03-23 19:19:24.960  9267  9267 E AndroidRuntime: FATAL EXCEPTION: main
03-23 19:19:24.960  9267  9267 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 9267
03-23 19:19:24.960  9267  9267 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:44)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.addAnalytics(App.kt:26)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:85)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
03-23 19:19:24.960  9267  9267 E AndroidRuntime: 	... 8 more
03-23 19:19:29.808  9305  9305 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x8000
03-23 19:19:29.811  9305  9305 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
03-23 19:19:29.955  9305  9305 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
03-23 19:19:30.418  9305  9350 E Perf    : Fail to get file list eu.kanade.tachiyomi.sy
03-23 19:19:30.418  9305  9350 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
03-23 19:19:30.418  9305  9350 E Perf    : Fail to get file list oat
03-23 19:19:30.419  9305  9350 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
03-23 19:19:30.662  9305  9382 E SQLiteLog: (284) automatic index on C(manga_id)
03-23 19:19:30.662  9305  9382 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on C(manga_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on merged(manga_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on ME(merge_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on C(merge_id)
03-23 19:19:30.722  9305  9382 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.sy/cache/chapter_disk_cache/56c086128781009d025b7e685d13fd8e.0: open failed: ENOENT (No such file or directory)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:496)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(HttpPageLoader.kt:37)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerPageHolder$setImage$2.invokeSuspend(PagerPageHolder.kt:6)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@40b398f, Dispatchers.Main]
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.Linux.open(Native Method)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	at libcore.io.IoBridge.open(IoBridge.java:482)
03-23 19:25:29.793  9305  9305 E GlobalExceptionHandler: 	... 9 more
03-23 19:25:29.997 11526 11526 E y:error_handle: Unknown bits set in runtime_flags: 0x8000
03-23 19:25:29.999 11526 11526 E y:error_handle: Not starting debugger since process cannot load the jdwp agent.
03-23 19:25:30.051 11526 11526 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
03-23 19:25:30.056 11526 11526 E AndroidRuntime: FATAL EXCEPTION: main
03-23 19:25:30.056 11526 11526 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy:error_handler, PID: 11526
03-23 19:25:30.056 11526 11526 E AndroidRuntime: java.lang.RuntimeException: Unable to create application eu.kanade.tachiyomi.App: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6587)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process eu.kanade.tachiyomi.sy:error_handler. Make sure to call FirebaseApp.initializeApp(Context) first.
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:44)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.addAnalytics(App.kt:26)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at eu.kanade.tachiyomi.App.onCreate(App.kt:85)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6582)
03-23 19:25:30.056 11526 11526 E AndroidRuntime: 	... 8 more
03-23 19:25:42.580 11609 11609 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x8000
03-23 19:25:42.585 11609 11609 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
03-23 19:25:42.703 11609 11609 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
03-23 19:25:43.118 11609 11656 E Perf    : Fail to get file list eu.kanade.tachiyomi.sy
03-23 19:25:43.118 11609 11656 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
03-23 19:25:43.119 11609 11656 E Perf    : Fail to get file list oat
03-23 19:25:43.119 11609 11656 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
03-23 19:25:43.217 11609 11683 E SQLiteLog: (284) automatic index on C(manga_id)
03-23 19:25:43.217 11609 11683 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on C(manga_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on merged(manga_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on ME(merge_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on C(merge_id)
03-23 19:25:43.253 11609 11683 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
App version: 1.9.0 (standard, c8c2d29f8, 48, 2023-03-21T00:06Z)
Preview build: 504
Android version: 10 (SDK 29)
Android build ID: QKQ1.190828.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: polaris
Device model: Mi MIX 2S
Device product name: polaris
```
### Tachiyomi version

1.9.0 preview build 504

### Android version

10

### Device

xiaomi mi mix 2s

### Other details

Havnet seen this specific issue so creating a ticket

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Try clearing chapter cache, otherwise give an example of a gallery

**Comment by patros36** [comment]
Clearing chapter cache didn't work unfortunately.
I found this out while browsing [Artist] - Hard-Degenerate on ExHentai.

**Comment by jobobby04** [comment]
Should be fixed in the latest builds
