### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Gokujo** [jobobby04/TachiyomiSY#856]
### Steps to reproduce

Update lib, generate Backup, read a title

### Expected behavior

Comfortable using of the app

### Actual behavior

I get a crash and have to restart the app

### Crash logs
```
--------- beginning of crash
04-16 21:18:15.322 11678 11898 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 21:18:15.322 11678 11898 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 11678
04-16 21:18:15.322 11678 11898 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:18:15.322 11678 11898 E AndroidRuntime: JSON input: 
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:18:15.322 11678 11898 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 21:18:53.855 14454 14723 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 14454
04-16 21:18:53.855 14454 14723 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:18:53.855 14454 14723 E AndroidRuntime: JSON input: 
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:18:53.855 14454 14723 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 21:18:53.880 14454 15374 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 14454
04-16 21:18:53.880 14454 15374 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:18:53.880 14454 15374 E AndroidRuntime: JSON input: 
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:18:53.880 14454 15374 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 21:18:53.881 14454 16245 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 14454
04-16 21:18:53.881 14454 16245 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:18:53.881 14454 16245 E AndroidRuntime: JSON input: 
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:18:53.881 14454 16245 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
04-16 21:21:32.261 18934 23591 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 18934
04-16 21:21:32.261 18934 23591 E AndroidRuntime: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:21:32.261 18934 23591 E AndroidRuntime: JSON input: 
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:21:32.261 18934 23591 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
--------- beginning of main
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: JSON input: 
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:21:32.261 18934 23591 E GlobalExceptionHandler: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: java.io.IOException: canceled due to kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: JSON input: 
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:89)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 	at java.lang.Thread.run(Thread.java:1012)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 	Suppressed: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the object '{', but had 'EOF' instead at path: $
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: JSON input: 
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:1)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:2)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:70)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:15)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:124)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:47)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:10)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:23)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:1)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at eu.kanade.tachiyomi.data.track.shikimori.OAuth$$serializer.deserialize(ShikimoriModels.kt:2)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:74)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at kotlinx.serialization.json.Json.decodeFromString(Json.kt:32)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at eu.kanade.tachiyomi.data.track.shikimori.ShikimoriInterceptor.intercept(ShikimoriInterceptor.kt:156)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at eu.kanade.tachiyomi.network.interceptor.UserAgentInterceptor.intercept(UserAgentInterceptor.kt:63)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:157)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:96)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:39)
04-16 21:21:32.261 18934 19121 E DispatchedCoroutine: 		... 3 more
04-16 21:21:32.390 23609 23633 E SQLiteLog: (283) recovered 37 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
04-16 21:21:35.401 23733 23782 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
App version: 1.9.0 (standard, d24a8d2, 46, 2023-02-04T23:26Z)
Preview build: 0
Android version: 13 (SDK 33)
Android build ID: T3B2.230316.005
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven

```
### Tachiyomi version

1.9.0

### Android version

Android 13

### Device

Google Pixel 6 Pro 

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.0](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi issue

**Comment by jobobby04** [comment]
You can lotout of shikimori for now until the fix is out

**Comment by Gokujo** [comment]
Ok, thx. I got massive crashes today on this behalf
