### ISSUE TITLE
App crashing when updating library 

### ISSUE THREAD

**Issue by Volern** [jobobby04/TachiyomiSY#897]
### Steps to reproduce

When updating library, the app starts the update, and after a few entries get updated, app crashes.

### Expected behavior

Should uodate

### Actual behavior

Crashes

### Crash logs

--------- beginning of perf
--------- beginning of system
--------- beginning of main
06-06 16:36:28.381 19497 19497 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x800000
06-06 16:36:28.390 19497 19497 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
06-06 16:36:28.558 19497 14524 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:28.581 19497 14528 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:28.585 19497 14528 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:28.590 19497 14528 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:28.616 19497 19497 E App     : Failed to modify notification channels
06-06 16:36:28.616 19497 19497 E App     : java.lang.SecurityException: Not allowed to delete channel library_progress_channel with a foreground service
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Parcel.createException(Parcel.java:2357)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Parcel.readException(Parcel.java:2340)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Parcel.readException(Parcel.java:2282)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:4213)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:912)
06-06 16:36:28.616 19497 19497 E App     : 	at androidx.core.app.NotificationManagerCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:1)
06-06 16:36:28.616 19497 19497 E App     : 	at androidx.core.app.NotificationManagerCompat$Api26Impl.deleteNotificationChannel(NotificationManagerCompat.java:1)
06-06 16:36:28.616 19497 19497 E App     : 	at eu.kanade.tachiyomi.data.notification.Notifications.createChannels(Notifications.kt:42)
06-06 16:36:28.616 19497 19497 E App     : 	at eu.kanade.tachiyomi.App.onCreate(App.kt:99)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Looper.loop(Looper.java:233)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.ActivityThread.main(ActivityThread.java:8030)
06-06 16:36:28.616 19497 19497 E App     : 	at java.lang.reflect.Method.invoke(Native Method)
06-06 16:36:28.616 19497 19497 E App     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-06 16:36:28.616 19497 19497 E App     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-06 16:36:28.616 19497 19497 E App     : Caused by: android.os.RemoteException: Remote stack trace:
06-06 16:36:28.616 19497 19497 E App     : 	at com.android.server.notification.NotificationManagerService$11.enforceDeletingChannelHasNoFgService(NotificationManagerService.java:3868)
06-06 16:36:28.616 19497 19497 E App     : 	at com.android.server.notification.NotificationManagerService$11.deleteNotificationChannel(NotificationManagerService.java:3881)
06-06 16:36:28.616 19497 19497 E App     : 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1813)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Binder.execTransactInternal(Binder.java:1165)
06-06 16:36:28.616 19497 19497 E App     : 	at android.os.Binder.execTransact(Binder.java:1134)
06-06 16:36:28.616 19497 19497 E App     : 
06-06 16:36:28.652 19497 19497 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
06-06 16:36:28.666 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:28.672 19497 14535 E SQLiteLog: (283) recovered 515 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
06-06 16:36:28.936 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on C(manga_id)
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on merged(manga_id)
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on ME(merge_id)
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on C(merge_id)
06-06 16:36:29.629 19497 14600 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-06 16:36:29.630 19497 14639 E SQLiteLog: (284) automatic index on C(manga_id)
06-06 16:36:29.630 19497 14639 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
06-06 16:36:30.569 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:30.574 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:30.586 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:38.723 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:36:38.778 19497 14531 E sqlite3_android: ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
06-06 16:37:16.179 19497 14535 E CursorWindow: Failed to read row 2493, column 0 from a CursorWindow which has 2493 rows, 14 columns.
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: java.lang.NullPointerException
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at tachiyomi.data.data.UpdatesViewQueriesImpl$updates$1.invoke(DatabaseImpl.kt:19)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at com.squareup.sqldelight.Query.executeAsList(Query.kt:18)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:6)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:12)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:63)
06-06 16:37:16.184 19497 19497 E GlobalExceptionHandler: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f5e3e5c, Dispatchers.Main.immediate]
06-06 16:40:32.284 22422 22422 E y:error_handle: Unknown bits set in runtime_flags: 0x800000
06-06 16:40:32.292 22422 22422 E y:error_handle: Not starting debugger since process cannot load the jdwp agent.
06-06 16:40:32.396 22422 22422 E App     : Failed to modify notification channels
06-06 16:40:32.396 22422 22422 E App     : java.lang.SecurityException: Not allowed to delete channel library_progress_channel with a foreground service
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Parcel.createException(Parcel.java:2357)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Parcel.readException(Parcel.java:2340)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Parcel.readException(Parcel.java:2282)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.INotificationManager$Stub$Proxy.deleteNotificationChannel(INotificationManager.java:4213)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.NotificationManager.deleteNotificationChannel(NotificationManager.java:912)
06-06 16:40:32.396 22422 22422 E App     : 	at androidx.core.app.NotificationManagerCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:1)
06-06 16:40:32.396 22422 22422 E App     : 	at androidx.core.app.NotificationManagerCompat$Api26Impl.deleteNotificationChannel(NotificationManagerCompat.java:1)
06-06 16:40:32.396 22422 22422 E App     : 	at eu.kanade.tachiyomi.data.notification.Notifications.createChannels(Notifications.kt:42)
06-06 16:40:32.396 22422 22422 E App     : 	at eu.kanade.tachiyomi.App.onCreate(App.kt:99)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Looper.loop(Looper.java:233)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.ActivityThread.main(ActivityThread.java:8030)
06-06 16:40:32.396 22422 22422 E App     : 	at java.lang.reflect.Method.invoke(Native Method)
06-06 16:40:32.396 22422 22422 E App     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
06-06 16:40:32.396 22422 22422 E App     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
06-06 16:40:32.396 22422 22422 E App     : Caused by: android.os.RemoteException: Remote stack trace:
06-06 16:40:32.396 22422 22422 E App     : 	at com.android.server.notification.NotificationManagerService$11.enforceDeletingChannelHasNoFgService(NotificationManagerService.java:3868)
06-06 16:40:32.396 22422 22422 E App     : 	at com.android.server.notification.NotificationManagerService$11.deleteNotificationChannel(NotificationManagerService.java:3881)
06-06 16:40:32.396 22422 22422 E App     : 	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1813)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Binder.execTransactInternal(Binder.java:1165)
06-06 16:40:32.396 22422 22422 E App     : 	at android.os.Binder.execTransact(Binder.java:1134)
06-06 16:40:32.396 22422 22422 E App     : 
06-06 16:40:32.429 22422 22422 E libprocessgroup: set_timerslack_ns write failed: Operation not permitted
06-06 16:40:32.433 22422 16802 E SQLiteLog: (283) recovered 309 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
App version: 1.9.3 (standard, 18d3615, 50, 2023-04-18T21:33Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: IN2023_15_220218
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus8Pro
Device model: IN2023
Device product name: OnePlus8Pro

### Tachiyomi version

1.9.3

### Android version

Android 11

### Device

OnePlus 8 Pro

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Fixed in the preview
