### ISSUE TITLE
Application crashes 

### ISSUE THREAD

**Issue by mozzaru** [jobobby04/TachiyomiSY#901]
### Steps to reproduce

Bug

### Expected behavior

Bug

### Actual behavior

Bug

### Crash logs
```
--------- beginning of system
--------- beginning of main
06-10 10:31:54.040 17885 17885 E de.tachiyomi.s: Unknown bits set in runtime_flags: 0x40000000
06-10 10:31:54.048 17885 17885 E de.tachiyomi.s: Not starting debugger since process cannot load the jdwp agent.
06-10 10:31:54.055 17885 17885 E RefClass: java.lang.reflect.InvocationTargetException
06-10 10:31:54.103 17885 17885 E libc    : Access denied finding property "ro.odm.prev.product.name"
06-10 10:31:54.387 17885 17924 E SQLiteLog: (283) recovered 464 frames from WAL file /data/user/0/eu.kanade.tachiyomi.sy/databases/tachiyomi.db-wal
06-10 10:31:54.396 17885 17929 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:54.694 17885 17930 E FA      : Failed to load metadata: Package name not found: android.content.pm.PackageManager$NameNotFoundException: org.chromium.chrome: cq.a(:com.google.android.gms.dynamite_measurementdynamite@231819037@23.18.19 (150400-0):0)
06-10 10:31:54.694 17885 17930 E FA      : Failed to load metadata: Metadata bundle is null
--------- beginning of crash
06-10 10:31:55.461 17885 17885 E AndroidRuntime: FATAL EXCEPTION: main
06-10 10:31:55.461 17885 17885 E AndroidRuntime: Process: eu.kanade.tachiyomi.sy, PID: 17885
06-10 10:31:55.461 17885 17885 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3729)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3896)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2326)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:263)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8299)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: Caused by: java.lang.NullPointerException
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourcePreferencesScreen.kt:35)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:72)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:27)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:41)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:137)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:27)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(BaseActivity.kt:98)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:24)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8146)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8130)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3698)
06-10 10:31:55.461 17885 17885 E AndroidRuntime: 	... 11 more
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.sy/eu.kanade.tachiyomi.ui.main.MainActivity}: java.lang.NullPointerException
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3729)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3896)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2326)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.os.Looper.loop(Looper.java:263)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.ActivityThread.main(ActivityThread.java:8299)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at java.lang.reflect.Method.invoke(Native Method)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: Caused by: java.lang.NullPointerException
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.browse.extension.details.SourcePreferencesFragment.onCreatePreferences(SourcePreferencesScreen.kt:35)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:72)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:27)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:41)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:137)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:58)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:34)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:27)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.base.activity.BaseActivity.onCreate(BaseActivity.kt:98)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at eu.kanade.tachiyomi.ui.main.MainActivity.onCreate(MainActivity.kt:24)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.Activity.performCreate(Activity.java:8146)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.Activity.performCreate(Activity.java:8130)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3698)
06-10 10:31:55.462 17885 17885 E GlobalExceptionHandler: 	... 11 more
06-10 10:31:55.613 17996 17996 E y:error_handle: Unknown bits set in runtime_flags: 0x40000000
06-10 10:31:55.619 17996 17996 E y:error_handle: Not starting debugger since process cannot load the jdwp agent.
06-10 10:31:55.625 17996 17996 E RefClass: java.lang.reflect.InvocationTargetException
06-10 10:31:55.668 17996 17996 E libc    : Access denied finding property "ro.odm.prev.product.name"
06-10 10:31:55.800 17996 18022 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:55.941 17996 18029 E cr_ManifestMetadata: App could not find itself by package name!
06-10 10:31:56.799 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.821 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.821 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.821 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.823 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.823 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.824 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.824 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.824 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.825 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.825 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
06-10 10:31:56.827 17996 18020 E libEGL  : Invalid file path for libcolorx-loader.so
App version: 1.9.3 (standard, 18d3615, 50, 2023-04-18T21:33Z)
Preview build: 0
Android version: 11 (SDK 30)
Android build ID: RMX2103_11_C.16
Device brand: realme
Device manufacturer: realme
Device name: RE50C1
Device model: RMX2103
Device product name: RMX2103T2
```
### Tachiyomi version

Last

### Android version

Android 11

### Device

Realme 7i

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jobobby04** [comment]
Known main Tachi issue
