### ISSUE TITLE
App still crashes when viewing gifs

### ISSUE THREAD

**Issue by patros36** [jobobby04/TachiyomiSY#913]
### Steps to reproduce

See issue 833, nothing changed unfortunately.

### Expected behavior

Not crash

### Actual behavior

Crash

### Crash logs

E/GlobalExceptionHandler: java.io.FileNotFoundException: /data/user/0/eu.kanade.tachiyomi.sy/cache/chapter_disk_cache/5c0bb64ccd015fdccfaa5334fd8f0f63.0: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at eu.kanade.tachiyomi.ui.reader.loader.HttpPageLoader$_loadPage$2.invoke(SourceFile:42)
	at eu.kanade.tachiyomi.ui.reader.viewer.pager.PagerPageHolder$setImage$2.invokeSuspend(SourceFile:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:113)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d49b979, Dispatchers.Main]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 9 more

### Tachiyomi version

1.9.3 r525

### Android version

android 1p

### Device

xiaomi mi mix 2s

### Acknowledgements

- [X] This is a TachiyomiSY specific issue that does not happen in [Tachiyomi Preview](https://github.com/tachiyomiorg/tachiyomi/).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://tachiyomi.org/help/faq/) and [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.9.3](https://github.com/jobobby04/tachiyomisy/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by SkillGG** [comment]
It crashes for me when reading normal chapters without gifs too

**Comment by jobobby04** [comment]
This is an issue with the main Tachi image cache, currently cannot do anything about it.
